---
- name: install nop commerce
  become: yes
  hosts: all
  tasks:
    - name: apt-get update
      apt:
        update_cache: yes
    - name: Install latest version of "openjdk-8-jdk"
      apt:
        name: openjdk-8-jdk
        state: latest
    - name: Creating mysql group
      ansible.builtin.group:
        name: mysql
        state: present
    - name: Creating user mysql and adding him to mysql group
      ansible.builtin.user:
        name: mysql
        groups: mysql
        append: yes
    - name: mysql
      get_url:
        url: https://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.46-linux-glibc2.12-x86_64.tar.gz
        dest: /home/ubuntu
    - name: Unarchive a file that is already on the remote machine
      unarchive:
        src: /home/ubuntu/mysql-5.6.46-linux-glibc2.12-x86_64.tar.gz
        dest: /usr/local
        remote_src: yes
    - name: install required packages for mysql
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
        - libaio1
        - libncurses5
        - libnuma-dev
    - name: Change ownership of mysql directory
      ansible.builtin.file:
        path: /usr/local/mysql
        owner: mysql
        group: mysql
        recurse: yes
        state: directory
    - name: Copy file
      ansible.builtin.copy:
        src: /usr/local/mysql-5.6.46-linux-glibc2.12-x86_64/
        dest: /usr/local/mysql/
        remote_src: yes
    - name: Change to mysql directory and run the shell script
      ansible.builtin.command:
        chdir: /usr/local/mysql
        cmd: scripts/mysql_install_db --user=mysql
    - name: Change ownership of mysql directory
      ansible.builtin.file:
        path: /usr/local/mysql
        owner: root
        recurse: yes
    - name: Change ownership of data directory
      ansible.builtin.file:
        path: /usr/local/mysql/data
        owner: mysql
        recurse: yes
    - name: Copying configuration file to different conf file
      ansible.builtin.copy:
        src: /usr/local/mysql/support-files/my-default.cnf
        dest: /etc/my.cnf
        remote_src: yes
    - name: Copying configuration file to different conf file
      ansible.builtin.copy:
        src: /usr/local/mysql/support-files/mysql.server
        dest: /etc/init.d/mysql.server
        remote_src: yes---
- name: install nop commerce
  become: yes
  hosts: all
  tasks:
    - name: apt-get update
      apt:
        update_cache: yes
    - name: Install latest version of "openjdk-8-jdk"
      apt:
        name: openjdk-8-jdk
        state: latest
    - name: Creating mysql group
      ansible.builtin.group:
        name: mysql
        state: present
    - name: Creating user mysql and adding him to mysql group
      ansible.builtin.user:
        name: mysql
        groups: mysql
        append: yes
    - name: mysql
      get_url:
        url: https://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.46-linux-glibc2.12-x86_64.tar.gz
        dest: /home/ubuntu
    - name: Unarchive a file that is already on the remote machine
      unarchive:
        src: /home/ubuntu/mysql-5.6.46-linux-glibc2.12-x86_64.tar.gz
        dest: /usr/local
        remote_src: yes
    - name: install required packages for mysql
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
        - libaio1
        - libncurses5
        - libnuma-dev
    - name: Change ownership of mysql directory
      ansible.builtin.file:
        path: /usr/local/mysql
        owner: mysql
        group: mysql
        recurse: yes
        state: directory
    - name: Copy file
      ansible.builtin.copy:
        src: /usr/local/mysql-5.6.46-linux-glibc2.12-x86_64/
        dest: /usr/local/mysql/
        remote_src: yes
    - name: Change to mysql directory and run the shell script
      ansible.builtin.command:
        chdir: /usr/local/mysql
        cmd: scripts/mysql_install_db --user=mysql
    - name: Change ownership of mysql directory
      ansible.builtin.file:
        path: /usr/local/mysql
        owner: root
        recurse: yes
    - name: Change ownership of data directory
      ansible.builtin.file:
        path: /usr/local/mysql/data
        owner: mysql
        recurse: yes
    - name: Copying configuration file to different conf file
      ansible.builtin.copy:
        src: /usr/local/mysql/support-files/my-default.cnf
        dest: /etc/my.cnf
        remote_src: yes
    - name: Copying configuration file to different conf file
      ansible.builtin.copy:
        src: /usr/local/mysql/support-files/mysql.server
        dest: /etc/init.d/mysql.server
        remote_src: yes